import { StyleSheet } from 'react-native';

export const friendProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
    minHeight: 56,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
    minHeight: 44,
    minWidth: 44,
  },
  backButtonText: {
    fontSize: 16,
    color: '#4A90E2',
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  removeButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    minHeight: 44,
  },
  removeButtonText: {
    fontSize: 14,
    color: '#FF3B30',
    fontWeight: '600',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 16,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#4A90E2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  avatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  avatarInitials: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  displayName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  levelText: {
    fontSize: 14,
    color: '#6C757D',
  },
  bioSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E9ECEF',
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6C757D',
    marginBottom: 4,
  },
  bioText: {
    fontSize: 14,
    color: '#495057',
    lineHeight: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 12,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionHeaderTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  sectionHeaderAction: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A90E2',
  },
  // Two-column preview container
  previewRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  previewColumn: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  previewColumnTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 8,
  },
  previewBox: {
    backgroundColor: '#E9ECEF',
    borderRadius: 8,
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewBoxTall: {
    backgroundColor: '#E9ECEF',
    borderRadius: 8,
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarPreviewCard: {
    backgroundColor: '#E9ECEF',
    borderRadius: 8,
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewImage: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  placeholderAvatarIcon: {
    marginBottom: 8,
  },
  placeholderHomeIcon: {
    marginBottom: 8,
  },
  placeholderText: {
    fontSize: 48,
  },
  placeholderLabel: {
    fontSize: 14,
    color: '#6C757D',
    textAlign: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#6C757D',
    textAlign: 'center',
  },
  overallStats: {
    gap: 12,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  statRowLabel: {
    fontSize: 14,
    color: '#6C757D',
  },
  statRowValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  workoutsList: {
    gap: 12,
  },
  workoutCard: {
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 12,
  },
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  workoutType: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  workoutDate: {
    fontSize: 12,
    color: '#6C757D',
  },
  workoutStats: {
    flexDirection: 'row',
    gap: 16,
  },
  workoutStat: {
    flex: 1,
  },
  workoutStatLabel: {
    fontSize: 11,
    color: '#6C757D',
    marginBottom: 2,
  },
  workoutStatValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  emptyWorkouts: {
    padding: 32,
    alignItems: 'center',
  },
  emptyWorkoutsText: {
    fontSize: 14,
    color: '#6C757D',
    textAlign: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#6C757D',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  errorText: {
    fontSize: 16,
    color: '#FF3B30',
    textAlign: 'center',
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: '#4A90E2',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
  },

  // Dashboard-style Buddy Card
  buddyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    position: 'relative',
    overflow: 'hidden',
  },
  progressBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: '#E9ECEF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#007AFF',
    borderTopLeftRadius: 20,
  },
  buddyAvatar: {
    width: 180,
    height: 180,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  buddyIdentity: {
    alignItems: 'center',
    marginBottom: 16,
  },
  buddyName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  buddySubtitle: {
    fontSize: 14,
    color: '#6C757D',
    marginBottom: 4,
  },
  buddyLevel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A90E2',
    marginBottom: 4,
  },
  buddyXpText: {
    fontSize: 13,
    color: '#6C757D',
  },
  streakBadge: {
    backgroundColor: '#FFF3CD',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 16,
  },
  streakIcon: {
    fontSize: 20,
    marginRight: 6,
  },
  streakText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#856404',
  },
  thisWeekSection: {
    borderTopWidth: 1,
    borderTopColor: '#E9ECEF',
    paddingTop: 16,
  },
  thisWeekTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6C757D',
    textTransform: 'uppercase',
    marginBottom: 12,
    textAlign: 'center',
  },
  thisWeekGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 8,
  },
  thisWeekStat: {
    flex: 1,
    alignItems: 'center',
  },
  thisWeekValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  thisWeekLabel: {
    fontSize: 11,
    color: '#6C757D',
    textAlign: 'center',
  },
});
